%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(router_pb).
-define(router_pb, true).

-define(router_pb_gpb_version, "4.4.0").


-endif.
