%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(user_pb).
-define(user_pb, true).

-define(user_pb_gpb_version, "4.4.0").

-ifndef('USER.LOGINREQ_PB_H').
-define('USER.LOGINREQ_PB_H', true).
-record('User.LoginReq',
        {email                  :: iodata(),        % = 1
         passwd                 :: iodata()         % = 2
        }).
-endif.

-ifndef('USER.LOGINRESP_PB_H').
-define('USER.LOGINRESP_PB_H', true).
-record('User.LoginResp',
        {res                    :: boolean() | 0 | 1, % = 1
         person                 :: user_pb:'User.Person'() | undefined % = 2
        }).
-endif.

-ifndef('USER.PERSON_PB_H').
-define('USER.PERSON_PB_H', true).
-record('User.Person',
        {id                     :: integer(),       % = 1, 32 bits
         name                   :: iodata(),        % = 2
         age                    :: integer(),       % = 3, 32 bits
         passwd                 :: iodata(),        % = 4
         email                  :: iodata(),        % = 5
         sex                    :: 'Male' | 'Female' | integer() | undefined % = 6, enum User.gender
        }).
-endif.

-ifndef('USER.RANGERESULT_PB_H').
-define('USER.RANGERESULT_PB_H', true).
-record('User.RangeResult',
        {persons = []           :: [user_pb:'User.Person'()] | undefined % = 1
        }).
-endif.

-ifndef('USER.RANGEREQUEST_PB_H').
-define('USER.RANGEREQUEST_PB_H', true).
-record('User.RangeRequest',
        {min_age                :: integer(),       % = 1, 32 bits
         max_age                :: integer()        % = 2, 32 bits
        }).
-endif.

-ifndef('USER.NAME_PB_H').
-define('USER.NAME_PB_H', true).
-record('User.Name',
        {name                   :: iodata()         % = 1
        }).
-endif.

-ifndef('USER.IDS_PB_H').
-define('USER.IDS_PB_H', true).
-record('User.Ids',
        {ids = []               :: [integer()] | undefined % = 1, 32 bits
        }).
-endif.

-endif.
